name: E2E Tests
on:
  push:
    branches:
      - main
      - fix/github_token_auth

permissions:
  contents: read

jobs:
  run-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.23
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Start Server
        run: |
          # Run the server in the background
          ./bin/ghcp server --address 127.0.0.1:8000 > /tmp/ghcp-server.log 2>&1 &

          # Wait for the server to start
          sleep 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_LOG_LEVEL: debug

      - name: Execute E2E Tests
        run: |
          # Run buf curl based tests
          buf curl -vv --protocol grpc --http2-prior-knowledge \
            --header "Authorization: Bearer $GHCP_AUTH_TOKEN" \
            --schema buf.build/safedep/api \
            http://localhost:8000/safedep.services.ghcp.v1.GitHubCommentsProxyService/CreatePullRequestComment \
            -d '{"owner": "safedep", "repo": "ghcp", "pr_number": "1", "body": "**E2E Test** Tag: 1234567890"}' 
        env:
          GHCP_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Server Logs
        if: ${{ always() }}
        run: sleep 2 && cat /tmp/ghcp-server.log

      - name: Stop Server
        run: |
          pkill -f "ghcp server"
