name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.23
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: make

      - name: Run Tests
        run: go test ./...

        


